#!/bin/bash

echo "🔧 Fixing 'Bad executable' error for NutritionTracker on physical iPhone device"
echo "=========================================================================="

# Navigate to the project directory
cd "$(dirname "$0")/NutritionTracker/NutritionTracker"

echo "📱 Problem Analysis:"
echo "- Your iPhone 15 is running iOS 18.6.2"
echo "- The app was targeting iOS 18.5 (now fixed to iOS 17.0)"
echo "- 'Bad executable' errors are typically caused by:"
echo "  • iOS deployment target mismatches"
echo "  • Code signing/provisioning profile issues"
echo "  • Corrupted build artifacts"
echo "  • App Groups entitlement configuration"
echo ""

echo "✅ Step 1: Deployment target fixed (iOS 18.5 → iOS 17.0)"
echo ""

echo "🧹 Step 2: Cleaning build artifacts..."
if [ -d "build" ]; then
    rm -rf build
    echo "   ✓ Removed build directory"
fi

if [ -d "DerivedData" ]; then
    rm -rf DerivedData
    echo "   ✓ Removed DerivedData directory"
fi

# Clean Xcode's DerivedData globally
echo "   • Cleaning Xcode DerivedData..."
rm -rf ~/Library/Developer/Xcode/DerivedData/*
echo "   ✓ Cleaned global DerivedData"

echo ""
echo "🔑 Step 3: Code Signing & Provisioning Profile Verification"
echo "Current settings:"
echo "- Bundle ID: TomerCode.NutritionTracker"
echo "- Widget Bundle ID: TomerCode.NutritionTracker.NutritionWidgetExtension"
echo "- Development Team: NM2982ZBF8"
echo "- Code Signing: Automatic"
echo "- App Groups: group.tomercode.nutritiontracker"
echo ""

echo "📋 MANUAL STEPS REQUIRED IN XCODE:"
echo "================================="
echo ""
echo "1. Open Xcode and navigate to your project"
echo "2. Select the 'NutritionTracker' target"
echo "3. Go to 'Signing & Capabilities' tab"
echo "4. Verify the following:"
echo "   • Team is set to your Apple Developer account"
echo "   • Bundle Identifier matches: TomerCode.NutritionTracker"
echo "   • 'Automatically manage signing' is checked"
echo "   • Provisioning Profile shows 'iOS Team Provisioning Profile'"
echo ""
echo "5. Select the 'NutritionWidgetExtension' target"
echo "6. Verify the same signing settings for the widget"
echo ""
echo "7. In the App Groups capability:"
echo "   • Ensure 'group.tomercode.nutritiontracker' exists"
echo "   • The group name should be consistent between main app and widget"
echo ""
echo "8. Connect your iPhone device"
echo "9. In Xcode, select your iPhone as the run destination"
echo "10. Trust the developer profile on your iPhone:"
echo "    Settings > General > VPN & Device Management > Developer App"
echo "    > Trust '[Your Apple ID]'"
echo ""

echo "🏗️ Step 4: Build and Install Commands"
echo "=================================="
echo ""
echo "Run these commands from the project directory:"
echo "cd NutritionTracker/NutritionTracker"
echo ""
echo "# Clean the project"
echo "xcodebuild clean -project NutritionTracker.xcodeproj -scheme NutritionTracker"
echo ""
echo "# Build for device (replace 'Your iPhone' with your device name)"
echo "xcodebuild -project NutritionTracker.xcodeproj -scheme NutritionTracker -destination 'platform=iOS,name=Your iPhone' build"
echo ""

echo "🚨 TROUBLESHOOTING TIPS:"
echo "======================="
echo ""
echo "If you still get 'Bad executable' error:"
echo ""
echo "1. VERIFY DEVICE TRUST:"
echo "   • Ensure your iPhone trusts this computer"
echo "   • When you connect iPhone, tap 'Trust' on the device"
echo ""
echo "2. CHECK PROVISIONING PROFILE:"
echo "   • In Xcode Project Navigator > Signing & Capabilities"
echo "   • Click on the provisioning profile dropdown"
echo "   • Ensure it shows a valid profile for your device"
echo ""
echo "3. APP GROUPS CONFIGURATION:"
echo "   • Both main app and widget must have the same App Group ID"
echo "   • The App Group must be enabled in your Apple Developer account"
echo "   • Group ID: group.tomercode.nutritiontracker"
echo ""
echo "4. RESET DEVICE PAIRING:"
echo "   • In Xcode: Window > Devices and Simulators"
echo "   • Right-click your device > Unpair Device"
echo "   • Reconnect and re-pair"
echo ""
echo "5. CHECK iOS VERSION COMPATIBILITY:"
echo "   • Your device: iOS 18.6.2"
echo "   • App target: iOS 17.0 (now compatible)"
echo ""
echo "6. BUNDLE IDENTIFIER CONFLICTS:"
echo "   • Ensure no other app with same bundle ID is installed"
echo "   • Delete any previous test versions from device"
echo ""

echo "✨ After following these steps, try running the app again from Xcode!"
echo ""
echo "Need more help? Check the detailed guides:"
echo "- INSTALL_ON_REAL_IPHONE.md"
echo "- SETUP_GUIDE.md"